replicaCount: 1

image:
  repository: terrafusionpro/api
  tag: "dev"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false

ingress:
  enabled: true
  hosts:
    - host: dev.terrafusion.pro
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: terrafusion-api-dev-tls
      hosts:
        - dev.terrafusion.pro

env:
  NODE_ENV: development
  LOG_LEVEL: debug
  ENABLE_METRICS: "true"

configMaps:
  app:
    enabled: true
    data:
      CORS_ALLOWED_ORIGINS: "https://dev.terrafusion.pro"
      API_VERSION: "v1"

postgresql:
  enabled: true
  auth:
    username: terrafusion
    database: terrafusion_dev
  primary:
    persistence:
      size: 10Gi