apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: terrafusion-api-ingress
  namespace: terrafusion-staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
  - hosts:
    - staging-api.terrafusion.pro
    secretName: terrafusion-api-staging-tls
  rules:
  - host: staging-api.terrafusion.pro
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: terrafusion-api
            port:
              number: 80