apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: monitoring
type: Opaque
data:
  admin-user: YWRtaW4=      # admin (base64 encoded)
  admin-password: SECRET_PLACEHOLDER  # To be replaced in CI/CD pipeline