apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pipeline-monitor
  namespace: monitoring
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: pipeline-metrics
      component: monitoring
  namespaceSelector:
    matchNames:
      - terrafusion-prod
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
    honorLabels: true
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'pipeline_(.*)'
      action: keep
    - sourceLabels: [stage]
      regex: '(.*)'
      targetLabel: pipeline_stage
      action: replace