apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: database-allow
  namespace: terrafusion-prod
spec:
  podSelector:
    matchLabels:
      app: postgresql
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: terrafusion
    ports:
    - protocol: TCP
      port: 5432