apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: monitoring-allow
  namespace: terrafusion-prod
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: terrafusion
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    - podSelector:
        matchLabels:
          app: prometheus
    ports:
    - protocol: TCP
      port: 8080
      # Metrics endpoint