apiVersion: v1
kind: Secret
metadata:
  name: terrafusion-db-credentials
  namespace: terrafusion
  labels:
    app: terrafusion-api
    environment: production
type: Opaque
# Values will be replaced during deployment by CI/CD pipeline
data:
  DATABASE_URL: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: terrafusion-api-credentials
  namespace: terrafusion
  labels:
    app: terrafusion-api
    environment: production
type: Opaque
# Values will be replaced during deployment by CI/CD pipeline
data:
  AI_SERVICE_API_KEY: ""