apiVersion: v1
kind: Secret
metadata:
  name: terrafusion-db-credentials
  namespace: terrafusion-production
type: Opaque
data:
  # These are example placeholders - real values should be provided by CI/CD or secrets management system
  database-url: BASE64_ENCODED_DATABASE_URL
  db-user: BASE64_ENCODED_DB_USER
  db-password: BASE64_ENCODED_DB_PASSWORD