apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "terrafusion.fullname" . }}-logs
  labels:
    {{- include "terrafusion.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "terrafusion.fullname" . }}-filebeat
  labels:
    {{- include "terrafusion.labels" . | nindent 4 }}
    app.kubernetes.io/component: logging
spec:
  selector:
    matchLabels:
      {{- include "terrafusion.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: logging
  template:
    metadata:
      labels:
        {{- include "terrafusion.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: logging
    spec:
      serviceAccountName: {{ include "terrafusion.serviceAccountName" . }}
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:8.7.1
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ELASTICSEARCH_HOST
          value: elasticsearch-master.monitoring.svc.cluster.local
        - name: ELASTICSEARCH_PORT
          value: "9200"
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: {{ include "terrafusion.fullname" . }}-filebeat-config
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      - name: data
        hostPath:
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "terrafusion.fullname" . }}-filebeat-config
  labels:
    {{- include "terrafusion.labels" . | nindent 4 }}
    app.kubernetes.io/component: logging
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: container
      paths:
        - /var/lib/docker/containers/*/*.log
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/lib/docker/containers/"
        - drop_event:
            when:
              not:
                has_fields: ['kubernetes.labels.app\\.kubernetes\\.io/name']

    processors:
      - add_cloud_metadata: ~
      - add_host_metadata: ~

    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}']
      indices:
        - index: "terrafusion-logs-%{+yyyy.MM.dd}"
      pipeline: geoip

    setup.template.name: "terrafusion"
    setup.template.pattern: "terrafusion-*"
    setup.ilm.enabled: true
    setup.ilm.policy_name: "terrafusion-logs-policy"
    setup.ilm.rollover_alias: "terrafusion-logs"