apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "terrafusion.fullname" . }}-network-policy
  labels:
    {{- include "terrafusion.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "terrafusion.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
    ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }}
  egress:
  # Allow DNS resolution
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow database access
  - to:
    {{- if .Values.postgresql.enabled }}
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: postgresql
    {{- else }}
    - ipBlock:
        cidr: 0.0.0.0/0 # Replace with specific RDS CIDR if known
    {{- end }}
    ports:
    - protocol: TCP
      port: 5432
  # Allow AI service API access
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0 # Replace with specific AI service CIDR if known
    ports:
    - protocol: TCP
      port: 443