apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "terrafusion.fullname" . }}-pdb
  labels:
    {{- include "terrafusion.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "terrafusion.selectorLabels" . | nindent 6 }}