{{- if .Values.secrets.app.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terrafusion.fullname" . }}-secret
  labels:
    {{- include "terrafusion.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.app.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}