{{- if .Values.secrets.database.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terrafusion.fullname" . }}-db-credentials
  labels:
    {{- include "terrafusion.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.database.data.DATABASE_URL | b64enc }}
{{- end }}

---
{{- if .Values.secrets.api.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terrafusion.fullname" . }}-api-credentials
  labels:
    {{- include "terrafusion.labels" . | nindent 4 }}
type: Opaque
data:
  AI_SERVICE_API_KEY: {{ .Values.secrets.api.data.AI_SERVICE_API_KEY | b64enc }}
{{- end }}